import os

BASE = "/root/GeminiMLB"

handlers = (
    "from telegram import Update\n"
    "from telegram.constants import ParseMode\n"
    "from telegram.ext import ContextTypes\n"
    "\n"
    "from app.bot.keyboards import home_keyboard, settings_keyboard\n"
    "from app.services.betting_service import BettingService\n"
    "from app.services.gemini_service import GeminiExplainer\n"
    "from app.services.odds_provider import MockOddsProvider\n"
    "from app.services.projection_engine import MockProjectionEngine\n"
    "from app.services.settings_store import InMemorySettingsStore\n"
    "from app.utils.formatting import fmt_bet_card, fmt_settings\n"
    "\n"
    "settings_store = InMemorySettingsStore()\n"
    "odds_provider = MockOddsProvider()\n"
    "projection_engine = MockProjectionEngine()\n"
    "betting_service = BettingService(projection_engine)\n"
    "gemini = GeminiExplainer()\n"
    "\n"
    "\n"
    "async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    text = '<b>MLB Value Bot</b>\\nTrack positive EV baseball bets with Kelly sizing and Gemini explanations.'\n"
    "    if update.message:\n"
    "        await update.message.reply_text(text, parse_mode=ParseMode.HTML, reply_markup=home_keyboard())\n"
    "\n"
    "\n"
    "async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    lines = [\n"
    "        '<b>Commands</b>',\n"
    "        '/today - Today slate',\n"
    "        '/bestbets - Positive EV bets',\n"
    "        '/settings - Settings',\n"
    "        '/bankroll 1000 - Set bankroll',\n"
    "        '/kelly 0.5 - Set Kelly fraction',\n"
    "        '/edge 0.02 - Set min edge',\n"
    "    ]\n"
    "    await update.message.reply_text('\\n'.join(lines), parse_mode=ParseMode.HTML)\n"
    "\n"
    "\n"
    "async def settings_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    user = settings_store.get(update.effective_user.id)\n"
    "    await update.message.reply_text(fmt_settings(user), parse_mode=ParseMode.HTML, reply_markup=settings_keyboard(user.explanations_enabled))\n"
    "\n"
    "\n"
    "async def today_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    await _send_bets(update, best_only=False)\n"
    "\n"
    "\n"
    "async def bestbets_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    await _send_bets(update, best_only=True)\n"
    "\n"
    "\n"
    "async def bankroll_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    if not context.args:\n"
    "        await update.message.reply_text('Usage: /bankroll 1000')\n"
    "        return\n"
    "    user = settings_store.update_bankroll(update.effective_user.id, float(context.args[0]))\n"
    "    await update.message.reply_text(fmt_settings(user), parse_mode=ParseMode.HTML)\n"
    "\n"
    "\n"
    "async def kelly_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    if not context.args:\n"
    "        await update.message.reply_text('Usage: /kelly 0.5')\n"
    "        return\n"
    "    user = settings_store.update_kelly(update.effective_user.id, float(context.args[0]))\n"
    "    await update.message.reply_text(fmt_settings(user), parse_mode=ParseMode.HTML)\n"
    "\n"
    "\n"
    "async def edge_command(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    if not context.args:\n"
    "        await update.message.reply_text('Usage: /edge 0.02')\n"
    "        return\n"
    "    user = settings_store.update_min_edge(update.effective_user.id, float(context.args[0]))\n"
    "    await update.message.reply_text(fmt_settings(user), parse_mode=ParseMode.HTML)\n"
    "\n"
    "\n"
    "async def callback_router(update: Update, context: ContextTypes.DEFAULT_TYPE):\n"
    "    query = update.callback_query\n"
    "    await query.answer()\n"
    "    user_id = update.effective_user.id\n"
    "    data = query.data\n"
    "    user = settings_store.get(user_id)\n"
    "    if data in {'home', 'refresh'}:\n"
    "        await query.edit_message_text('<b>MLB Value Bot</b>\\nUse the buttons below.', parse_mode=ParseMode.HTML, reply_markup=home_keyboard())\n"
    "    elif data == 'today':\n"
    "        await _send_bets(update, best_only=False, edit=True)\n"
    "    elif data == 'bestbets':\n"
    "        await _send_bets(update, best_only=True, edit=True)\n"
    "    elif data == 'settings':\n"
    "        await query.edit_message_text(fmt_settings(user), parse_mode=ParseMode.HTML, reply_markup=settings_keyboard(user.explanations_enabled))\n"
    "    elif data == 'toggle_gemini':\n"
    "        user = settings_store.toggle_explanations(user_id)\n"
    "        await query.edit_message_text(fmt_settings(user), parse_mode=ParseMode.HTML, reply_markup=settings_keyboard(user.explanations_enabled))\n"
    "    elif data == 'set_bankroll':\n"
    "        await query.edit_message_text('Send /bankroll 1000 with your preferred bankroll.', parse_mode=ParseMode.HTML)\n"
    "    elif data == 'set_kelly':\n"
    "        await query.edit_message_text('Send /kelly 0.5 for half Kelly, /kelly 0.25 for quarter Kelly.', parse_mode=ParseMode.HTML)\n"
    "    elif data == 'set_edge':\n"
    "        await query.edit_message_text('Send /edge 0.02 to require at least 2pct model edge.', parse_mode=ParseMode.HTML)\n"
    "\n"
    "\n"
    "async def _send_bets(update: Update, best_only: bool, edit: bool = False):\n"
    "    user = settings_store.get(update.effective_user.id)\n"
    "    games = await odds_provider.get_today_games()\n"
    "    bets = await betting_service.build_bets(games, user.bankroll, user.kelly_fraction, user.min_edge)\n"
    "    if best_only:\n"
    "        bets = bets[:5]\n"
    "    if not bets:\n"
    "        text = 'No positive EV bets met your current settings.'\n"
    "        if edit and update.callback_query:\n"
    "            await update.callback_query.edit_message_text(text, reply_markup=home_keyboard())\n"
    "        else:\n"
    "            await update.message.reply_text(text, reply_markup=home_keyboard())\n"
    "        return\n"
    "    header = '<b>Best Bets</b>' if best_only else '<b>Today\\'s Card</b>'\n"
    "    first = True\n"
    "    for bet in bets:\n"
    "        extra = ''\n"
    "        if user.explanations_enabled:\n"
    "            explanation = await gemini.explain_bet(bet.matchup, bet.model_prob, bet.implied_prob, bet.edge, bet.confidence_note)\n"
    "            extra = '\\n\\n<b>Gemini:</b> ' + explanation\n"
    "        body = (header + '\\n\\n' + fmt_bet_card(bet, user) + extra) if first else (fmt_bet_card(bet, user) + extra)\n"
    "        if edit and first and update.callback_query:\n"
    "            await update.callback_query.edit_message_text(body, parse_mode=ParseMode.HTML, reply_markup=home_keyboard())\n"
    "        else:\n"
    "            target = update.callback_query.message if update.callback_query else update.message\n"
    "            await target.reply_text(body, parse_mode=ParseMode.HTML, reply_markup=home_keyboard() if first else None)\n"
    "        first = False\n"
)

formatting = (
    "from html import escape\n"
    "from app.models.domain import BetView, UserSettings\n"
    "\n"
    "\n"
    "def pct(v: float) -> str:\n"
    "    return f'{v * 100:.1f}%'\n"
    "\n"
    "\n"
    "def money(v: float) -> str:\n"
    "    return f'${v:,.2f}'\n"
    "\n"
    "\n"
    "def fmt_bet_card(bet: BetView, settings: UserSettings) -> str:\n"
    "    lines = [\n"
    "        f'<b>{escape(bet.matchup)}</b>',\n"
    "        f'<i>{escape(bet.start_time_local)} - {escape(bet.sportsbook)}</i>',\n"
    "        '',\n"
    "        f'<b>Bet:</b> {escape(bet.side)} @ {bet.decimal_odds:.2f}',\n"
    "        f'<b>Model Win %:</b> {pct(bet.model_prob)}',\n"
    "        f'<b>Implied Win %:</b> {pct(bet.implied_prob)}',\n"
    "        f'<b>Edge:</b> {pct(bet.edge)}',\n"
    "        f'<b>EV:</b> {pct(bet.ev)}',\n"
    "        f'<b>Fair Odds:</b> {bet.fair_decimal_odds:.2f}',\n"
    "        f'<b>Kelly:</b> {pct(bet.kelly_fraction_raw)} raw / {pct(bet.kelly_fraction_used)} used',\n"
    "        f'<b>Stake:</b> {money(bet.stake_amount)} of {money(settings.bankroll)}',\n"
    "        f'<b>Note:</b> {escape(bet.confidence_note)}',\n"
    "    ]\n"
    "    return '\\n'.join(lines)\n"
    "\n"
    "\n"
    "def fmt_settings(settings: UserSettings) -> str:\n"
    "    on_off = 'On' if settings.explanations_enabled else 'Off'\n"
    "    lines = [\n"
    "        '<b>Your Settings</b>',\n"
    "        f'<b>Bankroll:</b> {money(settings.bankroll)}',\n"
    "        f'<b>Kelly Fraction:</b> {settings.kelly_fraction:.2f}',\n"
    "        f'<b>Min Edge:</b> {pct(settings.min_edge)}',\n"
    "        f'<b>Gemini Explanations:</b> {on_off}',\n"
    "    ]\n"
    "    return '\\n'.join(lines)\n"
)

import ast
ast.parse(handlers)
ast.parse(formatting)

with open(os.path.join(BASE, "app/bot/handlers.py"), "w") as f:
    f.write(handlers)
with open(os.path.join(BASE, "app/utils/formatting.py"), "w") as f:
    f.write(formatting)

print("Both files written and syntax verified OK")
